apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add bases (with a kustomization.yaml) to be applied to all clusters
- ../../bases/ # simply add bases (recurse to add all resources)


commonAnnotations:
  environment: all-clusters
