apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
# Add bases (with a kustomization.yaml) to be applied to all clusters
- ../../bases/machinesets/ # add machinesets
- ../../bases/infra_nodes/ # move resources to infra nodes


commonAnnotations:
  environment: all-clusters
